# Generated by Django 4.2.1 on 2023-05-18 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_alter_resumo_servico_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo_servico',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Cadastro_Cliente', to='agendamento.cadastro_carro'),
        ),
        migrations.AlterField(
            model_name='resumo_servico',
            name='placa_veiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Cadastro_Carro', to='agendamento.cadastro_carro'),
        ),
    ]
