# Generated by Django 4.2.1 on 2023-05-18 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_alter_resumo_servico_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_carro',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='agendamento.cadastro_cliente'),
        ),
    ]
