# Generated by Django 4.2.1 on 2023-05-18 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_alter_cadastro_carro_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo_servico',
            name='placa_veiculo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='agendamento.cadastro_carro'),
        ),
    ]
