# Generated by Django 4.2.1 on 2023-05-23 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0006_alter_resumo_servico_placa_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumo_servico',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agendamento.cadastro_cliente'),
        ),
        migrations.AlterField(
            model_name='resumo_servico',
            name='placa_veiculo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agendamento.cadastro_carro'),
        ),
    ]
